//|==========================================|
//|     Recommended Configs Descriptions     |
//|==========================================|

const JebediahsCommandDescription = 'Jebediah\'s Command is the flagship design of Untitled Space Craft. It features all of the inputs necessary to pilot a spacecraft from launch to landing, with plenty of quality-of-life upgrades over the traditional keyboard experience. Dual analog controls as well as a dedicated throttle module allow for fine control, while the full Navigation and Time modules ensure you won\'t have any reason to miss your keyboard. It is a controller fit for a thrillmaster extraordinaire.';
const ButtonBoxDescription = 'With dual joysticks, a throttle lever, and SAS controls, the USS Button Box provides a comprehensive piloting experience. It makes great use of the combined Navigation and Executive Actions modules, allowing it to compete with larger controllers in terms of functionality. And besides, who needs ten action groups when you forget to set them anyway?';
const KeyboardsLamentDescription = 'The Keyboard\'s Lament very nearly replaces every input available on the keyboard, with some added benefits to boot, such as full analog controls and action group state indicators, leading to a comprehensive experience that will leave your keyboard feeling lonely... at least until you have to name your spacecraft.';
const KeybCompanion1Description = 'While the Keyboard Companion might not be as flashy as the larger models, it can certainly add a lot to the keyboard experience. With the single-stick Analog Controls module, the full range of analog is at your fingertips. And with the combined Executive Actions module, you have plenty to immerse you, especially the Big Green Button for staging, not to mention that satisfying *click* of the SAS and RCS toggle switches.';
const KeybCompanion2Description = 'The Keyboard Companion 2 provides some much-needed enhancements to the keyboard experience. The single-stick Analog Controls module gives access to fine controls for both rotation and translation, while the Control Systems module grants access to inputs that aren\'t available on the keyboard, giving you maximum control while keeping a smaller profile.';
const ExtCommandSeat1Description = 'The External Command Seat provides a fairly comprehensive piloting experience, though the keyboard might still be worth keeping around for certain situations. The dual joysticks lead to a flashier controller with the ability to control both rotation and translation concurrently, while the combined Executive Actions and Navigation modules grant access to a wide range of controls for an immersive experience.';
const ExtCommandSeat2Description = 'The External Command Seat 2 is the definition of efficiency, making use of all of the combined modules which allows it to punch far above its weight class in terms of raw functionality. With the full suite of SAS functions, complete analog controls, and the more utilitarian Navigation module, not to mention a set of five action groups, it leaves no space unused.';
const ValentinasCommandDescription = 'While Valentina\'s Command is technically two controllers, these two Mark IV and Mark I containers can be linked together magnetically to form one larger container. A clever positioning of the modules can allow for a Telemetry module while keeping it from causing other displays to miss data. With an assortment of analog and digital inputs, this controller is a potent mix of control AND information.';
const MissionControlDescription = 'You\'re the kind of person who walks into a place and orders one of everything. We get it; you\'re probably a software developer or something. When your dual 4090 TIs aren\'t mining Bitcoin, they\'re contributing to your 10k hours in KSP, and you want me to do nothing for a whole month except make your Kerbal controller... and a very "Kerbal" one at that!';