






const JebediahsCommandDescription = 'This controller is the flagship design of Untitled Space Craft. It features all of the inputs necessary to pilot a spacecraft from launch to landing, with plenty of quality-of-life upgrades over the traditional keyboard experience. Dual analog controls as well as a dedicated throttle module allow for fine control, while the full Navigation and Time modules ensure you won\'t have any reason to miss your keyboard. It is a controller fit for a thrillmaster extraordinaire.';
const ButtonBoxDescription = 'With dual joysticks, a throttle lever, and SAS controls, the USS Button Box provides a comprehensive piloting experience. It makes great use of the combined Navigation and Executive Actions modules, allowing it to compete with larger controllers in terms of functionality. And besides, who needs ten action groups when you forget to set them anyway?';
const KeyboardsLamentDescription = 'This controller very nearly replaces every input available on the keyboard, with some added benefits to boot, such as full analog controls and action group state indicators. Though it doesn\'t have an EVA module, most of the EVA controls can be mapped to the Analog Controls module, leading to a comprehensive experience that will leave your keyboard feeling lonely... at least until you have to name your spacecraft.';
const KeybCompanion1Description = 'While Mark I containers might not be as flashy as the larger models, they can certainly add a lot to the keyboard experience. With the single-stick Analog Controls module, the full range of analog is at your fingertips. And with the combined Executive Actions module, you have plenty to immerse you, especially the Big Green Button for staging. Alternatively, you could swap it for a Control Systems module and gain access to inputs that aren\'t available on the keyboard.';
const KeybCompanion2Description = 'While Mark I containers might not be as flashy as the larger models, they can certainly add a lot to the keyboard experience. With the single-stick Analog Controls module, the full range of analog is at your fingertips. And with the combined Executive Actions module, you have plenty to immerse you, especially the Big Green Button for staging. Alternatively, you could swap it for a Control Systems module and gain access to inputs that aren\'t available on the keyboard.';
const ExtCommandSeat1Description = 'These two controllers, each identical in price, provide a fairly comprehensive piloting experience, though the keyboard might still be worth keeping around for certain situations. Depending on your play style, you can opt for dual joysticks and put the control systems on the Executive Actions module, or you can combine the sticks and have all of the SAS modes within reach as well as a few extra action groups.';
const ExtCommandSeat2Description = 'These two controllers, each identical in price, provide a fairly comprehensive piloting experience, though the keyboard might still be worth keeping around for certain situations. Depending on your play style, you can opt for dual joysticks and put the control systems on the Executive Actions module, or you can combine the sticks and have all of the SAS modes within reach as well as a few extra action groups.';
const ValentinasCommandDescription = 'While technically two controllers, these two Mark IV and Mark I containers can be linked together magnetically to form one larger container. A clever positioning of the modules can allow for a Telemetry module while keeping it from causing other displays to miss data. With an assortment of analog and digital inputs, this controller is a potent mix of control AND information.';
const MissionControlDescription = 'You\'re the kind of person who walks into a place and orders one of everything. We get it; you\'re probably a software developer or something. When your dual 4090 TIs aren\'t mining Bitcoin, they\'re contributing to your 10k hours in KSP, and you want me to do nothing for a whole month except make your Kerbal controller... and a very "Kerbal" one at that!';